// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyDKvgh4ZG4uzTi1K62pIkQTX24WhNi1V-E",
      authDomain: "icab-mobilidade.firebaseapp.com",
      projectId: "icab-mobilidade",
      storageBucket: "icab-mobilidade.appspot.com",
      messagingSenderId: "991315419560",
      appId: "1:991315419560:web:052ac3e1210afa5a4fbd9d",
      measurementId: "G-QB3RZBC23C");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqBW81KcM0oDg3rw6jw1y1GlGwnbu5DYY',
    appId: '1:991315419560:android:e646b99d58fb79114fbd9d',
    messagingSenderId: '991315419560',
    projectId: 'icab-mobilidade',
    storageBucket: 'icab-mobilidade.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyBNwJPL7JI2I_MXb8Fk8f-zxX0LoXNxcUM",
    authDomain: "icab-mobilidade.firebaseapp.com",
    projectId: "icab-mobilidade",
    storageBucket: "icab-mobilidade.appspot.com",
    messagingSenderId: "991315419560",
    appId: "1:991315419560:ios:26311ac9b1facabf4fbd9d",
    measurementId: "G-QB3RZBC23",
    androidClientId: '---------------------------',
    iosClientId: '--------------------',
    iosBundleId: '------------------',
  );

}
